<template>
  <div>
    <Header />
    <main>
      <h1 class="musictheory-header">
        Analysis of Scales in N-tone equal temperments
      </h1>
      <br />
      <p class="music-credit">By Luke Knotts | 31 May 2025</p>
      <hr />
      <ul>
        <li class="summary"><a href="#specs">Specifications</a></li>
        <li class="summary">
          <a href="#howto">How the PC Sets are Generated</a>
        </li>
        <li class="summary"><a href="#props">Properties Across Tunings</a></li>
        <ul>
          <li class="summary"><a href="#scale-count">Number of Scales</a></li>
          <li class="summary"><a href="#modes">Number of Modal Families</a></li>
        </ul>
      </ul>
      <hr />
      <p>
        Recently I experimented with generating all of the pc sets (pitch-class
        sets) for scales in some user-inputted edo.
      </p>
      <p>
        I will use "edo" as shorthand for tunings with equally spaced notes
        dividing an octave. The term itself is used for names like 12edo, which
        means "12 equal divisions of the octave".
      </p>
      <h1 class="musictheory-subheader" id="specs">Specifications</h1>
      <p>
        I am generating all of the unordered pc sets, starting on 0, which are
        possible in a given edo.
      </p>
      <p>
        A pc set is a way of representing notes where each number corresponds to
        a note. Because I care less about sets of notes which are just
        transpositions of each other, everything starts on 0.
      </p>
      <p>
        These sets are <i>unordered</i> in the sense that instead of listing
        both {0,1,2} and {0,2,1}, I only list {2,1,0}. Duplicate notes are not
        considered.
      </p>
      <p>
        However, a more unusual things I am doing is extending pc sets to an
        arbitrary number of possible notes per octave. To do this, each number
        represents the corresponding pitch in the tuning, or the number of
        <i>edo steps</i> to that particular note ("edo step" refers to the
        smallest interval in the tuning. In 12edo this is the semitone). While
        this method has the disadvantage of letting the same pc set have
        different meanings in different tunings, I don't think it will cause any
        problems.
      </p>
      <h1 class="musictheory-subheader" id="howto">
        How the PC Sets are Generated
      </h1>
      <p>
        To generate all of the pc sets, first the empty set and the one note set
        (which is {0}) are generated manually.
      </p>
      <p>
        From there, the 2-note sets are generated by creating every pair with 0
        and each integer up to one less than the number of notes availble
        (counting up to the number of notes is too many because we already
        started on 0).
      </p>
      <p>
        For instance, if we were generating sets in 5edo, the 2-note sets would
        be {0,1}, {0,2}, {0,3}, and {0,4}.
      </p>
      <p>
        From there, all of the 2-note sets are added to a list of "sets which
        can be used to make more sets". To make more sets from the existing
        sets, a function takes one set as an input, and produces new sets for
        each integer which can be appended to the input set. The resulting sets
        are then added back to the list of "sets which can be used to make more
        sets", and the inputted set is added to our main list of pc sets.
      </p>
      <p>
        Every additional pc set is created by applying our function to the sets
        in the list of "sets which can be used to make more sets" until there
        are no more sets to make new sets from.
      </p>
      <p>
        One of the nice things about this method is that once you specify the
        number of notes per octave, it can be used to generate the pc sets in
        all sorts of tunings like 19edo, 15edo, or 22edo (though my program
        takes a long time to calculate all 2 million scales in 22edo).
      </p>
      <h1 class="musictheory-subheader" id="props">
        Properties Across Tunings
      </h1>
      <br />
      <h1 class="musictheory-subsubheader" id="scale-count">
        - Number of Scales
      </h1>
      <p>
        After analyzing the results, it seems that the number of scales grows by
        a factor of 2 as a more possible notes are added to the tuning.
      </p>
      <p>
        For a tuning with 'n' notes, there seem to be 2^(n-1) scales in that
        tuning (not including the empty set). And if you imagine each possible
        note of the scale as a light that can be on or off, as
        <a class="inline-link" href="https://ianring.com/musictheory/scales/"
          >Ian Ring</a
        >
        describes, then it makes sense that the number of possible scales is
        like the number of possible binary numbers --assuming that the first
        'light' is on (so that the scale has a starting note).
      </p>
      <h1 class="musictheory-subsubheader" id="modes">- Modal Families</h1>
      <p>
        Getting a raw list of pc sets is a lot to handle, and so organizing it
        is nice. Modal families are groups of scales that are <i>modes</i> of
        each other, and are a common way of grouping up scales.
      </p>
      <p>When we count the number of modal families at different</p>
      <p>Including the empty set:</p>
      <p>start, edo=1</p>
      <p>2, 3, 4, 6, 8, 14, 20, 36, 60</p>
      <p>https://oeis.org/A000031</p>
      <Footer />
    </main>
  </div>
</template>
